let drugs = [];

//DOM Elements
const drugInput = document.getElementById('drugInput');
const drugListEl = document.getElementById('drugList');
const errorMsgEl = document.getElementById('errorMsg');
const checkBtn = document.getElementById('checkBtn');
const emptyState = document.getElementById('emptyState');
const resultCard = document.getElementById('resultCard');
const loadingSpinner = document.getElementById('loadingSpinner');
const btnText = document.getElementById('btnText');

// Function to Add a Drug
function addDrug() {
    const value = drugInput.value.trim();
    
    if (!value) return; // Stop if input is empty

    // Check for duplicates
    if (drugs.some(d => d.toLowerCase() === value.toLowerCase())) {
        showError('You have already added this medication.');
        return;
    }

    drugs.push(value);
    drugInput.value = ''; // Clear input box
    clearError();
    renderDrugs();
    hideResult(); // Hide previous results because the list changed
}

// Function to Remove a Drug
function removeDrug(index) {
    drugs.splice(index, 1);
    renderDrugs();
    hideResult();
}

// Function to Render the List on screen
function renderDrugs() {
    drugListEl.innerHTML = ''; // Clear current HTML inside list

    if (drugs.length === 0) {
        drugListEl.appendChild(emptyState);
        emptyState.style.display = 'block';
    } else {
        drugs.forEach((drug, index) => {
            const pill = document.createElement('div');
            pill.className = 'drug-pill';
            // Create pill with text and a remove button (x)
            pill.innerHTML = `
                ${drug}
                <button onclick="removeDrug(${index})">×</button>
            `;
            drugListEl.appendChild(pill);
        });
    }
}

async function checkInteractions() {
    if (drugs.length < 2) {
        showError('Please add at least two medications.');
        return;
    }

    startLoading();
    hideResult();
    clearError();

    const userQuery = `What is the interaction between ${drugs.join(' and ')}?`;

    try {
        const response = await fetch('http://localhost:3000/ask', { 
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            // UPDATE HERE: We send 'drugs' array along with the message
            body: JSON.stringify({ 
                message: userQuery,
                drugs: drugs 
            }) 
        });

        const data = await response.json();

        // Check if Python sent back our specific error flag
        if (data.is_error) {
            displayResult({
                severity: "Invalid Input",
                simple: data.reply, // "These are not legal medicines"
                technical: "The system only recognizes valid pharmaceutical drugs."
            });
        } else {
            // Normal AI Response
            displayResult({
                severity: "AI Analysis",
                simple: data.reply,
                technical: "Generated by Bio_ClinicalBERT + T5"
            });
        }

    } catch (error) {
        console.error("Error:", error);
        displayResult({
            severity: "Connection Error",
            simple: "Unable to contact the AI server.",
            technical: "Ensure medical_bot.py is running."
        });
    }
    stopLoading();
}

// Function to Display Results
function displayResult(data) {
    const severityBadge = document.getElementById('severityBadge');
    
    // Update text content
    document.getElementById('simpleExplanation').textContent = data.simple;
    document.getElementById('techExplanation').textContent = data.technical;
    severityBadge.textContent = data.severity + " RISK";

    // Update Colors based on severity
    resultCard.className = 'result-card'; // Reset classes
    if (data.severity === 'High') {
        resultCard.classList.add('theme-high');
    } else {
        resultCard.classList.add('theme-safe');
    }

    // Show the card
    resultCard.style.display = 'block';
}

// --- UTILITY FUNCTIONS ---

function showError(msg) {
    errorMsgEl.textContent = msg;
    setTimeout(() => { errorMsgEl.textContent = ''; }, 3000);
}

function clearError() {
    errorMsgEl.textContent = '';
}

function hideResult() {
    resultCard.style.display = 'none';
}

function startLoading() {
    checkBtn.disabled = true;
    loadingSpinner.style.display = 'inline-block';
    btnText.textContent = 'Analyzing...';
}

function stopLoading() {
    checkBtn.disabled = false;
    loadingSpinner.style.display = 'none';
    btnText.textContent = 'Check Interactions';
}

// Allow pressing "Enter" key to add drugs
drugInput.addEventListener('keypress', function (e) {
    if (e.key === 'Enter') {
        addDrug();
    }
});